name: nodeCI

on:
  push:
    branches:
      - main
      - docker
  pull_request:
    branches:
      - main
      - docker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir imagens
        run: docker compose build

      - name: Rodar testes
        run: docker compose run --rm app npm test

      - name: Limpar containers
        if: always()
        run: docker compose down