name: nodeCI

on:
  push:
    branches:
      - main
      - docker
  pull_request:
    branches:
      - main
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Compose
        run: docker-compose up -d db
      - name: Wait for Postgres to be healthy
        run: |
          for i in {1..10}; do
            docker-compose exec db pg_isready -U postgres && break
            sleep 5
          done
      - name: Build and run migrations
        run: docker-compose run --rm app npm run migrate
      - name: Build project
        run: docker-compose run --rm app npm run build
      - name: Run tests
        run: docker-compose run --rm app npm test